Classes/Repository/BrokenLinkRepository.php

Due to a typo no broken links were displayed in list.

[BUGFIX] Fix no broken links

---

Classes/Command/CheckLinksCommand.php

If the links are not checked for some reason (e.g. rootline is hidden),
the processing should not continue.
Previously, an exception was thrown.

[BUGFIX] Fix command if error in checking

---

Resources/Private/Partials/BrokenLinksGraphics.html

The float numbers (for percentage) should be displayed with only
2 positions after the decimal point. This was already done previously
in the table, but not in the SVG graphics.

[BUGFIX] Better formatting of floats

---

composer.json

TYPO3 9 is no longer supported so we do not need to use older
versions of the dev packages.

[TASK] Update composer dev dependencies

---

Classes/Linktype/ExternalLinktype.php
Classes/Linktype/FileLinktype.php
Classes/Linktype/InternalLinktype.php
Classes/View/BrofixReport.php
Resources/Private/Language/Module/de.locallang.xlf
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Backend/ReportTab.html

- Fix inconsistency of id and resname in some language files
- Use shortform of language key in "translate" ViewHelper. Due to
this the language file locallang.xlf and not Module/locallang.xlf
should be used.
- Add some missing language labels

[TASK] Clean up language labels

---

Classes/Mail/GenerateCheckResultFluidMail.php
Documentation/Changelog/Index.rst

If replytoemail was set, an undefined function was called which
resulted in an exception (and abort) on sending email after
checking links.
Resolves: #66

[BUGFIX] Fix calling undefined function

---

Classes/Command/CheckLinksCommand.php
Documentation/Changelog/Index.rst

If a depth=0 is set via the CLI command brofix:checklinks,
it is interpreted as unset option and the default is used.
Resolves: #69

[BUGFIX] Fix setting depth=0

---

Resources/Private/Partials/BrokenLinksStatsTable.html

The numbers should be aligned on the right side, the text on the
left. This is now fixed in the table of the email report (HTML
version).

[BUGFIX] Fix alignment in columns of Email report

---

Classes/Hooks/PageCalloutsHook.php
Classes/Repository/BrokenLinkRepository.php
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf

Previously we only showed if there were broken links in the page
module, not the number of broken links.
Now, the number of broken links are shown.

Show number of broken links in page module

---

Documentation/Changelog/Index.rst
Resources/Private/Partials/Pagination.html
Resources/Private/Templates/Backend/ReportTab.html

Show pagination controls on bottom of page.This was recently changed
in the core.
Show icon placeholders instead of disabled icons.

Optimize pagination

---

Classes/Repository/EditableRestriction.php

If no allowed languages are defined for a BE user / group
([allowed_languages] is not set), only broken links in
records of default language were shown for editors.
This is now fixed.
Releases: master
Resolves: #92

[BUGFIX] Fix EditableRestriction for allowed_languages

---

.github/workflows/ci.yml
Build/Scripts/runTests.sh
Build/phpunit/FunctionalTests.xml
Build/phpunit/FunctionalTestsBootstrap.php
Build/phpunit/UnitTests.xml
Build/phpunit/UnitTestsBootstrap.php
Build/testing-docker/docker-compose.yml
composer.json

This pull requests contains a handfull of commits to move the
brofix testing some steps forwared:
* activate push-triggered tests for all branches if ci workflow is
active in repositiory/fork.
* use typo3/testing-framework version compatible for v10/v11 testing
* integrate unit/functional testing into repository instead of using
template files from typo3/testing-framework
* update phpunit v8 to last minor as min req
* cleanup runTest.sh / adding support for php >= 8.0
* add tmpfs for executing sqlite functionals in ramdisk for file operations
* incorporate support for xdebug testing with macOS and WSL2
* update typo3/cms-* dependency versions
There are still tasks left, which will be addressed in dedicated pull-requests.

Move extension testing some steps forward

---

.github/workflows/ci.yml
Build/Scripts/ci.sh
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
Classes/LinkAnalyzer.php
Classes/Linktype/ExternalLinktype.php
Classes/View/BrofixReport.php
composer.json
ext_localconf.php

This pull-requests contains a collection of commits.
Mainly this collection pins down testing against v10
core only for now, but add first code fixes which are
need to have green v11 core testings.
Besides this, it adds option to jobs strategy to run
all job matrix mutations, even if some failes and avoids
cancellation of the others.
Further we add a scheduled test execution to test default
branch daily on the latest commit. This is helpful to find
out if dependencies release new versions which would than
lead to fails. Take this as a "nightly" test execution.
**Note:** You could see on my fork / branch that every commit
was green during going up these steps: 
https://github.com/sbuerk/brofix/commits/stefan-2

[TASK] pre-steps on the way to full v11 testing

---

Build/Scripts/ci.sh
Build/Scripts/cleanup.sh

composer require was not executed correctly, should be with
--no-update. We now remove the restoring of the version
because that would have to be updated continuously with the
versions in composer.json.
In any case, composer.json can be easily restored manually, e.g.
by git checkout composer.json.

cleanup.sh

---

.github/workflows/ci.yml

This pull-request restructues the github workflow, having one testset
per core version, exploded by matrix mutations (per core version).
We will also make sure all steps are executed, even if one step fails,
except it fails early (composer req/install), so we can get all failures
in one go, instead of fixing the first one, push, get next error etc.
Currently only one testset is included for core v10, which will get a
second testset later on for core v11 and php matrix for v11.
All steps are executed on push or pull_request. But no rules without
exceptions, and so we have some special conditions:
- phpstan (only for composerInstallMax steps/mutations)
- functional sqlite (only for nightly or pull_request, not for push)
- functional postgres (only for nightly or pull_request, not for push) …

[TASK] Restructure github workflows

---

Classes/View/BrofixReport.php
Classes/View/ManageExclusions.php

When changing the sorting order, the current page id was not considered.
Thus, this information was lost due to resulting it being set to 0.
This also resulted in problems as editor, because the editor does not
have access to page id 0, but the real problem was that the page id
was not set correctly.
Resolves: #133

[BUGFIX] Keep current page id in manage exclusions

---

.github/workflows/ci.yml
Build/phpunit/FunctionalTests.xml
Classes/Command/CheckLinksCommand.php
Tests/Functional/AbstractFunctionalTest.php
Tests/Functional/Command/CheckLinksCommandTest.php
Tests/Functional/LinkAnalyzerTest.php
Tests/Functional/Repository/BrokenLinkRepositoryTest.php

This pull-request contains two commits. The first one
refactors testcases to fix test setup issues, which 
are no longer compatible with core v11 testing. Most
of them are adaptopted from core changes preparing 
core testing with E_ALL and PHP 8.0/8.1 testing with
disabled exception/error handlers.
The second one adds out-commented entries to the ci
github action workflow as preparation, to be easier
enabled after last v11 core testing issue is analyzed
and fixed.
Anyway, running v11 tests could already be done locally
using `Build/Scripts/runTests.sh`, to analyze last core
v11 issue.

Fixes test-setup issues as preparation vor core v11 testing 

---

.github/workflows/ci.yml
Classes/LinkAnalyzer.php

This pull-request contains following points:
- Fix issue in LinkAnalyzer which failed on core v11
- Activate github CI testing against core v11 with PHP 7.4
Issue with LinkAnalzer was an incorrectly set parameter for
the softRef parser, which was invoked. This worked with v10
due an incorrect (unstrict) in_array() check in core, which
was fixed in core v11, thus failing now.
The first commit sets the parameter now correctly, which was
also fixed in core already for v11 for the core LinkAnalyzer.

Ensure LinkAnalzer works with core v11 (tests) and activate CI core v11 testing

---

.github/workflows/ci.yml
Build/Scripts/cglFixMyCommit.sh
Build/Scripts/checkComposerJsonForPushedMinimalPackage.sh
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
composer.json

This pull-requests enhance the testing capatibilities of this
repository with a bunch of changes.
- cgl & cglGit is runnable in runTests.sh and adjusted for the future
- Build/Scripts/cglFixMyCommit.sh added (needed for cglGit)
- raised friendsofphp/php-cs-fixer (needed for execution with PHP 8.0)
=>  in ci workflow disabled for PHP8.1 pro-activly, as there is no
compatible package yet available for PHP 8.1
- Rename option core versions selection from '-c' to '-t' in runTests.sh
and adjusted in github ci workflow
- added validation script to check if typo3/minimal was pushed in composer.json
- raised testing-framework:^6.15.1 and added PHP8.0/8.1 support to composer.json
Follow up would be to raise phpstan/phpstan with jangregor/phpstan-prophecy,
but this is not possible yet as this would …

[TASK] Enhance testing capatibilities

---

.github/workflows/ci.yml

This pull-requests enables testing against core v11 with PHP8.0 in github ci testing.
Nothing more to say here ;)

[TASK] Enable github ci testing for v11 / PHP8.0

---

Classes/CheckLinks/ExcludeLinkTarget.php
Classes/CheckLinks/LinkTargetCache/LinkTargetPersistentCache.php
Classes/DoctrineDbalMethodNameHelper.php
Classes/Repository/BrokenLinkRepository.php
Classes/Repository/ContentRepository.php
Classes/Repository/PagesRepository.php

There have been quite some changes between core v10 and v11, and used
doctrine/dbal versions with it's own transitions. Lately there were
some changes in the core facade classes, which now triggers phpstan
as calling old doctrine/methods on the new result interface fails as
there are no definitions anymore for the old methods like 'fetchColumn()',
'fetch()' or 'fetchAll()'.
Legacy installation of v10 ships a very old doctrine/dbal version without
support of the new methods, thus raising doctrine/dbal version as minimum
requirement would break support for v10 legacy installations.
To mitigate this, a small helper class is added to provide the corresponding
method named based on the installed core version, keeping full compatibility
about the whole version ranges but use the new methods on …

[BUGFIX] Avoid phpstan errors and use correct dbal methods per version

---

Build/phpstan.neon

Warning must be temporarily ignored until problem fixed in TYPO3
core.
Related: #150

[TASK] Add ignore rule for phpstan

---

composer.json

With composer >=2.2.0, allowed composer plugins have
to be added to composer.json as config/allowed_plugins.

[TASK] Set allowed composer plugins in composer.json

---

.github/workflows/ci.yml
Build/Scripts/runTests.sh
Build/phpstan.info.md
Build/phpstan.neon
Build/testing-docker/docker-compose.yml
composer.json

This patch streamlines the `Build/Scripts/runTests.sh`
setup and aligns corresponding `docker-compose.yml` to
incorporate recently changes added to `Typo3 Core` and
`ext:styleguide`.
* avoid `$HOME` directory volume mount from host to container
* avoid mounting `/etc/passwd` and `/etc/group` from host to container
* replace CORE_ROOT with ROOT_DIR in docker-compose.yml
* remove CORE_ROOT determination from 'Build/Scripts/runTests.sh'
* use `.Build/.cache` as `COMPOSER_CACHE_DIR`
* use `.Build/.cache/phpstan` as phpstan tmp folder
* use root folder as base for phpstan relative paths in configuration
and adjust corresponding `working_dir` for docker container
* explicitly define `Build/phpstan.neon` as entrypoint for phpstan
check with `Build/Scripts/runTests.sh -s phpstan`
* display …

[TASK] Streamline runTests.sh and docker-compose.yml

---

Build/phpstan/phpstan-baseline.neon
composer.json

Raises core constraints to released versions and regenerate phpstan
baseline file, as corresponding bugfixes has been added and making
ignore patterns in the baseline file superflous now.
used commands:
```bash
$ composer req "typo3/cms-backend":"^10.4.24 || ^11.5.6" --no-update
$ composer req "typo3/cms-core":"^10.4.24 || ^11.5.6" --no-update
$ composer req "typo3/cms-fluid":"^10.4.24 || ^11.5.6" --no-update
$ composer req "typo3/cms-info":"^10.4.24 || ^11.5.6" --no-update
$ Build/Scripts/runTests.sh -s phpstanGenerateBaseline
```
and as second patch phpstan is raised:
```bash
$ composer req phpstan/phpstan:"^1.4.5" --dev --no-update
```

[TASK] Raise core versions "^10.4.24 || ^11.5.6"

---

Classes/Controller/BrokenLinkListController.php

Previously, when filtering page links via "clickfilter", the full
URL was used. However, instead, the original URL from the database
field tx_brofix_broken_link_fixer.url should be used.

[BUGFIX] Fix filtering of page links

---

Classes/Controller/BrokenLinkListController.php

Query parameters must be evaluation in initialization phase.

[BUGFIX] Fix initialization order

---

Classes/Controller/BrokenLinkListController.php
Classes/Controller/Filter/BrokenLinkListFilter.php

The current setting was not stored when switching to another
page in the page tree. This is now fixed.
Resolves: #185

[BUGFIX] Fix view mode

---

Classes/Controller/BrokenLinkListController.php
Classes/Util/StringUtil.php
Resources/Private/Templates/Backend/BrokenLinkList.html

There are 2 last check values stored in the database:
1. When the link target (URL) was last checked
2. When the element was last checked
Because of the (external) link target cache being used, these two values
may differ.
However showing both values, may be confusing and may offer little
additional values for the editors.
We now show the oldest of the 2 values, which will either be the
same for both values or most likely be the last checked time of the
link target.

[TASK] Merge 2 lastcheck column into one

---

Classes/Controller/BrokenLinkListController.php
Classes/Controller/Filter/BrokenLinkListFilter.php
Classes/Repository/BrokenLinkRepository.php
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Templates/Backend/BrokenLinkList.html
Resources/Public/JavaScript/Brofix.js

It is now possible to select how to match the URL in a select box.
It is possible to select from the following:
- partial: This is a partial match of the URL (LIKE %url%)
- exact: The URL entered in the input field must match exactly
- no partial match: This is the opposite of partial match, all
broken link records which do not match the URL via partial
match are displayed
- no exact match: This is the opposite of the exact match, all
broken link records which do not match the URL exactly are
displayed.

[FEATURE] Add URL match selection

---

Resources/Private/Templates/Backend/BrokenLinkList.html

Remove extra line break which resulted in too much padding in the
top of the module.

Remove extra line break in module

---

Resources/Private/Templates/Backend/BrokenLinkList.html

Use the same text (link target) for the text of the link target
which is also used as column header in the column we are
filtering. Otherwise, this is confusing.
The text for the column header was previously replaced.

Replace text for filter link target

---

Resources/Public/Icons/Extension.svg

The previous icon (displayed in the left column of the module)
contained the "link" symbol and a check mark. This was a good
symbol for the extension, but it was crowed and made the icon
look weird compared to other icons with more padding.
Now, we use an icon with only the "link" symbol.

Add new icon

---

Classes/Controller/BrokenLinkListController.php
Classes/Controller/Filter/BrokenLinkListFilter.php
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Templates/Backend/BrokenLinkList.html

The tooltips for the filter are not fixed. Previously one of them
had the text "Show only results ..." and the other had "Show only
broken links ...". We now always use "Show broken links ...".

Fix text inconsistencies

---

Resources/Private/Templates/Backend/BrokenLinkList.html

Use "Element" instead of "Element UID" as this is shorter and the
UID text is already used as placeholder.

Optimize text for element filter

---

Classes/Controller/BrokenLinkListController.php
Classes/Controller/ManageExclusionsController.php
Tests/Functional/AbstractFunctionalTest.php
Tests/Functional/CheckLinks/ExcludeLinkTargetTest.php
Tests/Functional/LinkAnalyzerTest.php
Tests/Functional/Repository/BrokenLinkRepositoryTest.php
Tests/Functional/Repository/PagesRepositoryTest.php
composer.json

Fixed some warnings due to changes in typo3/testing-framework and
phpstan.
Raised phpstan and testing-framework.
composer require typo3/testing-framework:^6.16.5
composer require phpstan/phpstan:^1.7.2

Fix phpstan warnings

---

.github/workflows/ci.yml
Build/Scripts/ci.sh
Build/Scripts/cleanup.sh
Build/Scripts/runTests.sh
CONTRIBUTING.md
README.md
composer.json
ext_emconf.php

A branch typo3_10_dev has been created so that bugfixes can
be backported, but the main branch no longer supports TYPO3
v10. Dependencies and test scripts were modified accordingly.

!!![TASK] Drop TYPO3 v10 support

---

Build/phpstan/phpstan-baseline.neon
Build/phpunit/FunctionalTests.xml
Build/phpunit/UnitTests.xml
Build/testing-docker/docker-compose.yml
Classes/CheckLinks/ExcludeLinkTarget.php
Classes/CheckLinks/LinkTargetCache/LinkTargetPersistentCache.php
Classes/LinkAnalyzer.php
Classes/Linktype/InternalLinktype.php
Classes/Repository/BrokenLinkRepository.php
Classes/Repository/ContentRepository.php
Classes/Repository/EditableRestriction.php
Classes/Repository/ExcludeLinkTargetRepository.php
Classes/Repository/PagesRepository.php
Tests/Functional/Repository/BrokenLinkRepositoryTest.php
Tests/Unit/AbstractUnitTest.php
Tests/Unit/Linktype/ExternalLinktypePreprocessUrlTest.php
Tests/Unit/Linktype/ExternalLinktypeTest.php
composer.json

This pull-requests contains multiplepatches. Main goal is
to align the testing to TYPO3 v11 core constraints, which
basically means to use phpunit v9 instead of phpunit v8.
Needed adjustments and solving @todo's in config files are
done to get a new minimum baseline testing after dropping
TYPO3 v10 support.
Additional @todo is added to functional testing configuration
file to activate proper constant to remove errorhandler which
hides away quite some errors, after e.g. `BrokenLinkRepository`
is modernized and incorporates latest changes in v11 regarding
deprecated softref parses (which throws silenced depreceration
error messages).
Additionally the pull-request contains a patch which change the
soft reference parsing to the new DI parsers to avoid deprecation
messages along with full DI …

[TASK] Align testing to TYPO3 v11 core constraints and changes

---

Classes/BackendSession/BackendSession.php
Classes/Controller/BrokenLinkListController.php
Classes/Controller/Filter/BrokenLinkListFilter.php
Classes/Controller/Filter/ManageExclusionsFilter.php
Classes/Controller/ManageExclusionsController.php
Classes/Repository/ExcludeLinkTargetRepository.php
Classes/Util/Arrayable.php

Session data will be passed as array. Use generic interface to
handle conversions.
This also fixes a possible exception with incomplete objects
being returned as session data.
Resolves: #208
Releases: main

[BUGFIX] Streamline session data

---

.github/workflows/ci.yml
Build/Scripts/runTests.sh

Use specific `github error formatting` for `phpstan`
error reporing in `github actions`. This adds the
phpstan errors directly into the file view on pull
requests for better readability.
For direct pushes
on commit level it directly extracts and shows the
errors in the pane instead of only in the command
line view.
> **Note:** images are not from this repo, so do not be confused with stated filenames.

[TASK] Use phpstan github error format in github actions

---

ext_localconf.php

This makes it easier for extension to supply a drop-in replacement for specific Linktypes without having to change the page TSconfig.
Resolves: #221

[FEATURE] Only set Linktypes if not already set

---

Classes/Controller/UiHelper/UserSettings.php

Fix problem of uninitialized array key with PHP 8.1

Fix uninitialized array key when accessing user settings

---

composer.json

This is no longer being used by the composer installers and should be removed.

[TASK] Remove "cms-package-dir" from composer.json

---

.github/workflows/ci.yml

We do not want the scheduled workflow to run in every fork of this repository because it is only necessary to run it once in the main repo.

[TASK] Execute scheduled CI workflow only in main repo

---

Classes/Controller/BrokenLinkListController.php

Switch the first 2 parameters (message and title) so that function works the same way as TYPO3 FlashMessage constructor.

[BUGFIX] Fix order in createFlashMessage

---

Build/phpunit/FunctionalTests.xml
Build/testing-docker/docker-compose.yml
Tests/Functional/AbstractFunctional.php
Tests/Functional/CheckLinks/ExcludeLinkTargetTest.php
Tests/Functional/CheckLinks/LinkTargetCache/LinkTargetPersistentCacheTest.php
Tests/Functional/Command/CheckLinksCommandTest.php
Tests/Functional/LinkAnalyzerTest.php
Tests/Functional/Repository/BrokenLinkRepositoryTest.php
Tests/Functional/Repository/PagesRepositoryTest.php

The functional tests were not run because the class name did not have a Test suffix.

[TASK] Fix functional tests

---

Classes/LinkAnalyzer.php

When checking custom tables which have a TCA setup of `['ctrl']['label'] = 'uid'` with PHP 8 you end up with an TypeError (aborting the whole process):
`trim(): Argument #1 ($string) must be of type string, int given`
The reason is that `BackendUtility::getProcessedValue` returns the integer, despite it's phpdoc stating `@return string|null`.
So casting it to a string is the easiest solution, which would also cope with a potential "null" headline being returned.
Resolves #277

[BUGFIX] TypeError on trim() when TCA label points to "uid" (PHP 8)

---

Classes/Linktype/InternalLinktype.php
Tests/Functional/Fixtures/input_content_with_not_broken_page_link_with_anchor.xml
Tests/Functional/Fixtures/input_content_with_not_broken_page_link_with_anchor_in_header_link.xml
Tests/Functional/LinkAnalyzerTest.php

Links to pages with anchor (e.g. "t3://page?uid=1#22") in non-RTE fields (e.g. tt_content.header_link) were falsely detected as broken. This is now fixed.
Additionally, functional tests were added to cover this in the future.
Resolves: #284
Releases: main, 11.5

[BUGFIX] Fix checking page links with anchors

---

Classes/Linktype/InternalLinktype.php
Tests/Functional/Fixtures/input_content_with_not_broken_page_link_with_anchor.xml
Tests/Functional/Fixtures/input_content_with_not_broken_page_link_with_anchor_in_header_link.xml
Tests/Functional/LinkAnalyzerTest.php

Links to pages with anchor (e.g. "t3://page?uid=1#22") in non-RTE fields (e.g. tt_content.header_link) were falsely detected as broken. This is now fixed.
Additionally, functional tests were added to cover this in the future.
Resolves: #284
Releases: main, 11.5

[BUGFIX] Fix checking page links with anchors (#286) - v12 / main

---

.github/workflows/ci.yml
Classes/Hooks/PageCalloutsHook.php

Because of CSP, it is not possible to open the module via JavaScript. We open it using UriBuilder.

[BUGFIX] Fix page_callouts behaviour for TYPO3 v12

---

Classes/CheckLinks/CrawlDelay.php
Classes/Configuration/Configuration.php
Configuration/TsConfig/Page/pagetsconfig.tsconfig
Documentation/Setup/TsconfigReference.rst

E.g. by using this in TSconfig:
mod.brofix.crawlDelay.nodelay = regex:/(.*\.)?example.(org|com)/
Using nodelay, it is possible to exclude local domains from crawlDelay.

Make it possible to use regex in crawlDelay.nodelay

---

Classes/LinkAnalyzer.php

The function getSelectFields used 'tt_content' instead of the $table variable in one place, which might result in exceptions if checking other tables.

[BUGFIX] Use table variable in getSelectFields

---

Classes/LinkAnalyzer.php

The function getSelectFields used 'tt_content' instead of the $table variable in one place, which might result in exceptions if checking other tables.

[BUGFIX] Use table variable in getSelectFields (#304)

---

Classes/Configuration/Configuration.php
Classes/FormEngine/FieldShouldBeCheckedWithFlexform.php
Classes/LinkAnalyzer.php
Classes/Parser/LinkParser.php
Documentation/Changelog/Entries/6.x/Feature-Support-checking-in-flexforms.rst
Documentation/Setup/Reference.rst
ext_conf_template.txt
ext_localconf.php

Make some changes to previous feature of modifying TCA processing to check for Flexform: The TCA processing is made configurable. This can be configured in the Extension Configuration, since this is considered a system-wide configuration and should no be overridden by TSconfig.
For processing Flexforms it is currently necessary to choose tcaProcessing="full" in the Extension Configuration.
The previous Changelog is updated accordingly.

[FEATURE] Make TCA processing configurable

---

Classes/Configuration/Configuration.php
Classes/FormEngine/FieldShouldBeCheckedWithFlexform.php
Classes/LinkAnalyzer.php
Classes/Parser/LinkParser.php
Documentation/Changelog/Entries/6.x/Feature-Support-checking-in-flexforms.rst
Documentation/Setup/ExtensionConfigurationReference.rst
ext_conf_template.txt
ext_localconf.php

* [FEATURE] Make TCA processing configurable
Make some changes to previous feature of modifying TCA processing to check for Flexform: The TCA processing is made configurable. This can be configured in the Extension Configuration, since this is considered a system-wide configuration and should no be overridden by TSconfig.
For processing Flexforms it is currently necessary to choose tcaProcessing="full" in the Extension Configuration.
The previous Changelog is updated accordingly.

[FEATURE] Make TCA processing configurable (#311)

---

Classes/CheckLinks/CheckLinksStatistics.php
Classes/Command/CheckLinksCommand.php
Classes/Configuration/Configuration.php
Classes/LinkAnalyzer.php
Classes/Repository/BrokenLinkRepository.php
Configuration/TsConfig/Page/pagetsconfig.tsconfig
Documentation/Changelog/Entries/6.x/Feature-Make-configurable-when-to-send-email.rst
Documentation/Setup/Commands.rst
Documentation/Setup/TsconfigReference.rst

There are 2 ways to influence if / when an email is sent after link checking via cli / scheduler
1. the option send-email (short: -e) in the cli / scheduler command
2. TSconfig mod.brofix.mail.sendOnCheckLinks
We now add some more options for better control when emails are sent:
* "**never**" : never send email (previously: 0)
* "**always**": send email (previously: 1)
* "**any**"   : send email if any broken links were found
* "**new**"   : send email if new broken links were found
* "**auto**"  : do not override, use TSconfig
Effectively, using the option in the command overrides the TSconfig configuration, unless "auto" is used.
If one wants to change the behaviour for each site individually, it is possible to configure this via TSconfig and run the command with -send-email auto.
See …

[FEATURE] Add configuration options for sending email

---

Classes/CheckLinks/CheckLinksStatistics.php
Classes/Command/CheckLinksCommand.php
Classes/Configuration/Configuration.php
Classes/LinkAnalyzer.php
Classes/Repository/BrokenLinkRepository.php
Configuration/TsConfig/Page/pagetsconfig.tsconfig
Documentation/Changelog/Entries/6.x/Feature-Make-configurable-when-to-send-email.rst
Documentation/Setup/Commands.rst
Documentation/Setup/Index.rst
Documentation/Setup/TsconfigReference.rst

There are 2 ways to influence if / when an email is sent after
link checking via cli / scheduler
1. the option send-email (short: -e) in the cli / scheduler
command
2. TSconfig mod.brofix.mail.sendOnCheckLinks
We now add some more options for better control when emails
are sent:
* "**never**" : never send email (previously: 0)
* "**always**": send email (previously: 1)
* "**any**"   : send email if any broken links were found
* "**new**"   : send email if new broken links were found
* "**auto**"  : do not override, use TSconfig
Effectively, using the option in the command overrides the
TSconfig configuration, unless "auto" is used.
If one wants to change the behaviour for each site individually,
it is possible to configure this via TSconfig and run
the command with -send-email auto.
See …

Feature make email configurable (v11.5)

---

Classes/LinkAnalyzer.php

This may prevent exception if processing flexform fields without using tcaProcessing = 'full'.
Processing Flexforms should still be performed with tcaProcessing ='full' though.

[BUGFIX] Add list_type to list of select fields if tt_content

---

ext_conf_template.txt

- Use only one colon (":") in the label to separate label from description
- Use categories to create multiple tabs
- Order the options so that options for newer versions are at the bottom (for easier backports)
- Add some better descriptions
- Add the default values

[BUGFIX] Fix extension configuration

---

ext_conf_template.txt

- Use only one colon (":") in the label to separate label from description
- Use categories to create multiple tabs
- Order the options so that options for newer versions are at the bottom (for easier backports)
- Add some better descriptions
- Add the default values

[BUGFIX] Fix extension configuration (#325)

---

Classes/LinkAnalyzer.php

$GLOBALS['TCA'][$table]['ctrl'] must be used to determine which field in the database table contains the timestamp (tstamp) and header. Previously, the field names "header" and "timetamp" were used directly, which is not correct.
Resolves: #308

[BUGFIX] Correctly read fields from records in recheck function

---

Classes/Controller/BrokenLinkListController.php
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Templates/Backend/BrokenLinkList.html

Previously we showed the last check time for URL and record separately. Since then, it was unified into one field but this can be confusing.
Because of the link target cache and how checking is performed, the last check time for the record and the URL may differ, so they should be shown separately.

[TASK] Show time for last check URL and record again

---

Classes/Command/CheckLinksCommand.php

Since $GLOBALS['TYPO3_REQUEST'] may be used in some lowlevel TCA processing routines (e.g. in news), it is necessary to initialize this global variable. However, this was done incorrectly.

[BUGFIX] Fix initialization of TYPO3_REQUEST in command

---

Build/Scripts/runTests.sh
Classes/Command/CheckLinksCommand.php

Since $GLOBALS['TYPO3_REQUEST'] may be used in some lowlevel TCA processing routines (e.g. in news), it is necessary to initialize this global variable. However, this was done incorrectly.

[BUGFIX] Fix initialization of TYPO3_REQUEST in command (v11.5)

---

Classes/Configuration/Configuration.php
Classes/Controller/BrokenLinkListController.php
Documentation/Changelog/Entries/6.x/Features-Make-it-possible-to-edit-full-record.rst
Documentation/Setup/ExtensionConfigurationReference.rst
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_extconf.xlf
Resources/Private/Partials/BrokenLinkList.html
ext_conf_template.txt

Previously, there was a button in the link list to edit the field where the broken link is contained. It is now possible - via extension configuration - to show:
- only button to edit the field
- button to edit entire record (element)
- or both
In some cases, e.g. for sys_redirect records it is helpful to have more context and edit the entire record.
Resolves: #352

[FEATURE] Add button to edit entire record

---

Documentation/Setup/ExtensionConfigurationReference.rst
ext_conf_template.txt

Use tab name "Report" instead of "Backend" in Extension Configuration.

[TASK] Rename tab to "Report" in extension configuration

---

Classes/Repository/EditableRestriction.php

Do some checking before accessing fields in TCA in EditableRestriction. In particular, $GLOBALS['TCA'][$table]['ctrl']['type'] may contain a type which does not correspond to a field (such as 'uid_local:type' for sys_file_reference.
Fixing this makes it possible to add sys_file_reference to list of tables to check, e.g.
mod.brofix.searchFields.sys_file_reference = link
Resolves: #358

[BUGFIX] Fix array access in EditableRestriction

---

Classes/Controller/BrokenLinkListController.php
Resources/Private/Partials/BrokenLinkList.html

In the link list, there is a button to jump to the page layout. This will now open the page layout in the current language of the record containing the broken link.

[FEATURE] Jump to page layout in correct language

---

Classes/LinkAnalyzer.php
Classes/Repository/EditableRestriction.php

- always write the type to element_type, if available
- only use $GLOBALS['TYPO3_CONF_VARS']['BE']['explicitADmode'] for tt_content, otherwise use $GLOBALS['TCA'][$table]['columns'][$type]['config']['authMode']
- if no autMode is set, do not add any checks for it to EditableRestriction
This should fix a known problem, that broken links in tx_domain_model_news records were not displayed for non-admin editors
Resolves: #369

[BUGFIX] Better handling of type/authMode with permission checks

---

Classes/Repository/BrokenLinkRepository.php

Since TYPO3 v6, a check_status was introduced to store various link checking results in the database (not just the broken links). This must now be checked as well.
The bug manifested itself in the RTE, where all links were shown as broken.

[BUGFIX] Fix checken for broken link in EventListener

---

Classes/CheckLinks/CrawlDelay.php
Classes/CheckLinks/LinkTargetResponse/LinkTargetResponse.php
Classes/Linktype/ExternalLinktype.php
Tests/Unit/CheckLinks/CrawlDelayTest.php

If status code 429 ("Too many requests") or 403 ("Service unavailable") is returned, we should stop checking URLs for this domain.
Additionally, the header "Retry-After" is handled.
The URLs are marked as "Cannot check".
Resolves: #420

[FEATURE] Handle HTTP status code 429 and 503

---

Classes/CheckLinks/LinkTargetResponse/LinkTargetResponse.php
Classes/Controller/BrokenLinkListController.php
Classes/LinkAnalyzer.php
Classes/Linktype/ExternalLinktype.php
Classes/Linktype/LinktypeInterface.php
Resources/Private/Partials/BrokenLinkList.html
Tests/Functional/CheckLinks/LinkTargetCache/LinkTargetPersistentCacheTest.php
ext_conf_template.txt

In case of external URLs, there may be one or more redirects. The redirect target is now displayed. This has the following advantages:
- provide more clarity in case of confusing response codes, such as TLS errors for http-urls
- redirects are more visible
- in case of 429 or 503, there is a mechanism to stop checking further URLs. However, this should be applied to the effective domain, not the original domain

[FEATURE] The redirect target is now displayed (if there are redirects)

---

Classes/Configuration/Configuration.php
Classes/Controller/BrokenLinkListController.php
Classes/LinkAnalyzer.php
composer.json
ext_conf_template.txt

Previously all links were rechecked after editing which could cause unnecessary delays. Also, it is not always necessary since it is usually sufficient to check if the links still exist in the record on editing.
This can now be controlled with the option recheckLinksOnEditing.

[TASK] Make rechecking links after editing optional

---

Classes/LinkAnalyzer.php

Use executeStatement() or executeQuery(), may lead to exception with v13.
Resolves: #443

[BUGFIX] Do not call querybuilder::execute()
