Documentation/Installation/Index.rst

[DOCS] Fix install command example

---

.github/workflows/ci.yml

Tests are no longer run twice if feature branch opened in this
repo (by push and pull being executed).
resolves #79

[BUGFIX] Do not run tests twice

---

Classes/View/ManageExclusions.php
Gruntfile.js
Resources/Private/Sass/brofix_manage_exclusions.scss
Resources/Private/Templates/Backend/ManageExclusions.html
Resources/Public/Css/brofix_manage_exclusions.css

Use same principles and CSS for manage exclusion table, in order to
- Avoid scrollbars: use fixed table layout
- Make sure the URL word breaks
- Include CSS
Resolves: #127

[BUGFIX] Render table fixed for manage exclusions

---

Classes/Command/CheckLinksCommand.php
Classes/Repository/PagesRepository.php

Add exclusion checking by uid in CLI

Add exclusion checking by uid in CLI

---

.github/workflows/ci.yml
Build/phpstan.neon
Classes/CheckLinks/LinkTargetCache/AbstractLinkTargetCache.php
Classes/CheckLinks/LinkTargetCache/LinkTargetCacheInterface.php
Classes/LinkAnalyzer.php
Classes/Repository/PagesRepository.php
Classes/View/BrofixReport.php
Classes/View/ManageExclusions.php
Tests/Functional/AbstractFunctionalTest.php
composer.json

- raise phpstan to ^1.2
- add PHP 8.1 to GitHub ci.yml
- fix errors which existed before but were not reported previously by phpstan

[TASK] Prepare PHP 8.1 testing

---

Classes/Filter/Filter.php
Classes/Repository/BrokenLinkRepository.php
Classes/View/BrofixReport.php
Classes/View/ManageExclusions.php

The list for managing the exclusions must take
permissions into account.
Resolves: #118

[BUGFIX] Add permission checks for exclusions

---

Classes/Filter/Filter.php
Classes/Repository/BrokenLinkRepository.php
Classes/Repository/ExcludeLinkTargetRepository.php
Classes/View/BrofixReport.php
Classes/View/ManageExclusions.php
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Templates/Backend/ManageExclusions.html
Resources/Private/Templates/Backend/ReportTab.html

- add texts
- move exlude list database queries to separate repository

Refactor exclude list

---

Build/phpstan/phpstan-baseline.neon
Classes/Controller/AbstractInfoController.php
Classes/Controller/BrokenLinkListController.php
Classes/Controller/Filter/BrokenLinkListFilter.php
Classes/Controller/Filter/ManageExclusionsFilter.php
Classes/Controller/ManageExclusionsController.php
Classes/Hooks/PageCalloutsHook.php
Classes/Repository/BrokenLinkRepository.php
Classes/Repository/ExcludeLinkTargetRepository.php
Configuration/Backend/AjaxRoutes.php
Configuration/Backend/Routes.php
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Backend/ManageExclusions.html
Resources/Public/Css/brofix_manage_exclusions.css
Resources/Public/JavaScript/ManageExclusions.js
Tests/Functional/Repository/BrokenLinkRepositoryTest.php
ext_tables.php

This solves problem of flickering because both lists were
previously loaded as once and the switch performed per
JavaScript.
Also, the code is cleaned up with more separation between the
two modules.
Resolves: #134

[TASK] Separate Broken link list and manage exclusions

---

Classes/Controller/BackendUser/BackendUserInformation.php
Classes/Controller/BrokenLinkListController.php
Classes/Controller/ManageExclusionsController.php
Resources/Private/Templates/Backend/ManageExclusions.html

BE user should only get access to exlusion list if the BE user
has access to tx_brofix_exclude_link_target.

[BUGFIX] Fix permissions for exclusion list

---

Resources/Private/Language/Module/locallang.xlf
Resources/Private/Language/Module/locallang_db.xlf
Resources/Private/Language/locallang.xlf

- Add matching resname for all language labels

[TASK] Fix language labels

---

Classes/Hooks/PageCalloutsHook.php
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Language/Module/locallang_db.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Backend/BrokenLinkList.html

UI improvements

---

Documentation/Installation/Index.rst

In one file, Includes.txt was included instead of Includes.rst.txt

Fix documentation

---

Classes/Controller/BrokenLinkListController.php
Classes/Hooks/DataHandlerHook.php
Classes/Repository/EditableRestriction.php

It seems php-cs-fixer has fixed some bugs or changed
rules which now applies in checks.
This change adds the changed cgl based on the auto
cgl fix using php-cs-fixer.
Used command:
> Build/Scripts/runTests.sh -s cgl

[TASK] Apply fixed cgl issues

---

composer.json

Raise current phpstan min version to current
version ^1.8.2.

[TASK] Raise phpstan/phpstan ^1.8.2

---

Resources/Private/Templates/Backend/ManageExclusions.html

Make it possible to edit an Exclude record in the
"Manage Exclusions" list.
Resolves: #227
cc @gaumontp

[FEATURE] Add edit button in "Manage Exclusions"

---

Resources/Private/Sass/brofix.scss
Resources/Private/Templates/Backend/BrokenLinkList.html
Resources/Public/JavaScript/Brofix.js

Use similar HTML elements and classes as redirects module to have a more unified styling and behaviour.

[TASK] Clean up user interface

---

.github/workflows/ci-functional.yml
Classes/Linktype/InternalLinktype.php
composer.json

[BUGFIX] Fix wrong errorType for InternalLinkType (TYPO3 9)

---

Classes/Controller/BrokenLinkListController.php
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Templates/Backend/BrokenLinkList.html

[FEATURE] Add link text to table

---

Classes/Configuration/Configuration.php
Classes/LinkAnalyzer.php
Classes/Repository/ContentRepository.php
Configuration/TsConfig/Page/pagetsconfig.tsconfig
Documentation/Setup/Reference.rst

Follow up PR for #261 (could not push onto the branch Quebecca/brofix:main).

Add configuration option for workspaces

---

Classes/Controller/AbstractBrofixController.php
Classes/Controller/BrofixController.php
Classes/Controller/BrokenLinkListController.php
Classes/Controller/ManageExclusionsController.php

Remove
- ShortcutButton::setGetVariables
- ShortcutButton::setModuleName
- ShortcutButton::setSetVariables
Resolves: #253

[TASK] Remove deprecated functionality

---

Build/phpunit/FunctionalTests.xml
Tests/Functional/AbstractFunctional.php
Tests/Functional/CheckLinks/ExcludeLinkTargetTest.php
Tests/Unit/AbstractUnit.php
Tests/Unit/CheckLinks/CrawlDelayTest.php
Tests/Unit/Configuration/ConfigurationTest.php
Tests/Unit/Linktype/ExternalLinktypeTest.php
composer.json

```
composer require typo3/testing-framework:^7.0.2 --dev 
composer require typo3/cms-core:^11.5.28 typo3/cms-backend:^11.5.28 typo3/cms-fluide:^11.5.28
```

Raise version dependencies

---

Classes/Controller/ManageExclusionsController.php

[BUGFIX] Fix exception in Export CSV file

---

.github/workflows/build.yml
CONTRIBUTING.md
Gruntfile.js
package.json

- grunt should be >= 1.5.2
- node-sass should be >= 7.0.0

[SECURITY] Update grunt and node-sass

---

.github/workflows/build.yml
CONTRIBUTING.md
Gruntfile.js
package.json

https://github.com/sypets/brofix/pull/291

Update node security (v11)

---

Classes/Command/CheckLinksCommand.php
Classes/Controller/BrokenLinkListController.php
Classes/LinkAnalyzer.php
Classes/Linktype/AbstractLinktype.php
Classes/Linktype/ExternalLinktype.php
Classes/Mail/GenerateCheckResultFluidMail.php
Classes/Parser/LinkParser.php
Classes/Util/TcaUtil.php
Documentation/Changelog/Entries/6.x/Feature-Support-checking-in-flexforms.rst
Tests/Functional/Repository/BrokenLinkRepositoryTest.php
ext_localconf.php
ext_tables.sql

!!! This feature can be used and has been tested, but should be considered experimental until further notice!
Since Flexforms consist of nested fields, checking these kind of fields need modified functionality.
See corresponding Changelog for more information.
Resolves: #248
Resolves: #249

[FEATURE] Add support for checking flexforms

---

Documentation/Setup/ExtensionConfigurationReference.rst

Add documentation for all available options

[DOCS] Extend Extension Configuration docs

---

Classes/Command/CheckLinksCommand.php
Documentation/Setup/Commands.rst

Make it possible to pass seperal -p options in the cli command (same as -x).

[TASK] Unify -p option

---

Classes/Command/CheckLinksCommand.php
Documentation/Setup/Commands.rst

Make it possible to pass seperal -p options in the cli command (same as -x).

[TASK] Unify -p option (#330)

---

Classes/Controller/BrokenLinkListController.php
Resources/Private/Language/Module/locallang.xlf

Use new language labels and default to old language labels for the last_check headers.

[BUGFIX] Fix language labels for last_check headers

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

Change runTests.sh script to either use docker-compose or docker compose, depending on what is on the system.

[TASK] Use docker composer or docker-compose

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

Change runTests.sh script to either use docker-compose or docker compose, depending on what is on the system.

[TASK] Use docker composer or docker-compose (v11.5)

---

Classes/Command/CheckLinksCommand.php

Call session initialization onlu in the CLI mode.

[BUGFIX] Fix #362: exception in scheduler

---

Classes/Configuration/Configuration.php
Classes/Controller/BrokenLinkListController.php
Documentation/Changelog/Entries/6.x/Feature-AddButtonToJumpToPageLayout.rst
Resources/Private/Partials/BrokenLinkList.html
ext_conf_template.txt

todos
- should use latest version of page_callouts

Add button for jumping to page layout

---

Classes/Parser/LinkParser.php

[BUGFIX] Fix undefined array key in analyzeLinks

---

Classes/Controller/Filter/BrokenLinkListFilter.php

[BUGFIX] Set URL filter to empty string by default

---

Classes/Controller/BrokenLinkListController.php
Classes/Controller/ManageExclusionsController.php
Configuration/JavaScriptModules.php
Resources/Public/JavaScript/Backend/Modules/Brofix.js
Resources/Public/JavaScript/Backend/Modules/ManageExclusions.js

[TASK] Remove requirejs

---

Classes/Controller/BrokenLinkListController.php

Using AbstractMessage or FlashMessage for this purpose is deprecated since v12.

Use ContextualFeedbackSeverity for message severity

---

Classes/Configuration/Configuration.php
Tests/Functional/AbstractFunctional.php
Tests/Functional/CheckLinks/ExcludeLinkTargetTest.php

[TASK] Remove unused function

---

Classes/Parser/LinkParser.php

[BUGFIX] Parse page links with anchor correctly

---

Classes/Parser/LinkParser.php

[BUGFIX] Additional fix in parse page links

---

Classes/Parser/LinkParser.php

[BUGFIX] Exlude rtehtmlarea_images softref parser

---

Classes/Linktype/InternalLinktype.php
Classes/Parser/LinkParser.php
Classes/Parser/SoftReference/TypolinkRecordTagSoftReferenceParser.php
Resources/Private/Language/Module/locallang.xlf

[BUGFIX] Allow checking of record links

---

Classes/EventListener/CheckBrokenRteLinkEventListener.php
Classes/LinkAnalyzer.php
Classes/Linktype/InternalLinktype.php
Classes/Parser/LinkParser.php
Classes/Parser/SoftReference/TypolinkRecordTagSoftReferenceParser.php
Configuration/Services.yaml
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Partials/BrokenLinkList.html

[BUGFIX] Fixed detection of several record links

---

Classes/Controller/Filter/BrokenLinkListFilter.php
Resources/Private/Partials/BrokenLinkList.html
Resources/Private/Partials/BrokenLinksForm.html

- setting the filter is now visualized as buttons
- increase size of X to remove filter
- only show "Remove all filter" button if any filter is applied
- add icons

[TASK] Improve handling of filter in report

---

Classes/Hooks/DataHandlerHook.php

Fix exception with PHP 8.4 in DataHandlerHook
